//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.1

pub use super::last_update::ActiveModel as LastUpdateActiveModel;
pub use super::last_update::Entity as LastUpdateEntity;
pub use super::nostr_event::ActiveModel as NostrEventActiveModel;
pub use super::nostr_event::Column as NostrEventColumn;
pub use super::nostr_event::Entity as NostrEventEntity;
